using System.Collections.Generic;
using Mergistry.Data;
using UnityEngine;

namespace Mergistry.Models.Combat
{
    /// <summary>
    /// Defines the enemy composition for a single combat encounter.
    /// Pre-generated by MapGeneratorService when the floor map is created.
    /// A7: also carries optional RoomModifier and pit positions.
    /// </summary>
    public class CombatSetup
    {
        public List<EnemySpawnInfo> Enemies  { get; } = new List<EnemySpawnInfo>();

        // A7: room modifier
        public RoomModifierType     Modifier     { get; set; } = RoomModifierType.None;
        public List<Vector2Int>     PitPositions { get; }      = new List<Vector2Int>();
    }

    /// <summary>
    /// Spawn definition for a single enemy in a combat encounter.
    /// </summary>
    public class EnemySpawnInfo
    {
        public EnemyType Type;
        public int       HP;
        public int       ArmorPoints;
        public int       BombTimer;

        public EnemySpawnInfo(EnemyType type, int hp, int armorPoints = 0, int bombTimer = 3)
        {
            Type        = type;
            HP          = hp;
            ArmorPoints = armorPoints;
            BombTimer   = bombTimer;
        }
    }
}
