using System.Collections.Generic;
using Mergistry.Data;

namespace Mergistry.Models.Combat
{
    /// <summary>
    /// Defines the enemy composition for a single combat encounter.
    /// Pre-generated by MapGeneratorService when the floor map is created.
    /// </summary>
    public class CombatSetup
    {
        public List<EnemySpawnInfo> Enemies { get; } = new List<EnemySpawnInfo>();
    }

    /// <summary>
    /// Spawn definition for a single enemy in a combat encounter.
    /// </summary>
    public class EnemySpawnInfo
    {
        public EnemyType Type;
        public int       HP;
        public int       ArmorPoints;
        public int       BombTimer;

        public EnemySpawnInfo(EnemyType type, int hp, int armorPoints = 0, int bombTimer = 3)
        {
            Type        = type;
            HP          = hp;
            ArmorPoints = armorPoints;
            BombTimer   = bombTimer;
        }
    }
}
