using Mergistry.Data;
using Mergistry.Models.Map;

namespace Mergistry.Models
{
    /// <summary>
    /// Tracks persistent run state shared across states.
    /// HP is saved on CombatState.Exit and restored on CombatState.Enter.
    /// FloorMap is generated by MapState when null; cleared on reset or floor advance.
    /// </summary>
    public class RunModel
    {
        public int          CurrentFight    { get; set; } = 0;   // increments each combat victory
        public int          CurrentFloor    { get; set; } = 0;   // 0,1,2 — controls element pool (3/4/5)
        public int          PersistentHP    { get; set; } = 5;
        public bool         LastVictory     { get; set; } = false;

        // A4: map navigation
        public FloorMapModel FloorMap       { get; set; } = null;
        public int           CurrentNodeId  { get; set; } = -1;  // -1 = at entrance
        public MapNodeType   CurrentNodeType{ get; set; } = MapNodeType.Combat;

        public void Reset()
        {
            CurrentFight    = 0;
            CurrentFloor    = 0;
            PersistentHP    = 5;
            LastVictory     = false;
            FloorMap        = null;
            CurrentNodeId   = -1;
            CurrentNodeType = MapNodeType.Combat;
        }
    }
}
